# Generated by Django 3.1.1 on 2020-09-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200906_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todocreater',
            new_name='user',
        ),
    ]
