# Generated by Django 3.1.1 on 2020-09-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200907_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='creator',
        ),
    ]
